### ISSUE TITLE
Failing to initialize FixedNumberPostConnector with RandomDistribution for weights

### ISSUE THREAD

**Issue by sbillaudelle** [NeuralEnsemble/PyNN#256]
When I initialize a FNPostC with a RandomDistribution as source for the synaptic weights, I receive the following traceback:

``` python
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    proj = pynn.Projection(pre, post, conn)
  File "/opt/software/pynn/0.7.4/lib/python2.6/site-packages/pyNN/nest/__init__.py", line 332, in __init__
    method.connect(self)
  File "/opt/software/pynn/0.7.4/lib/python2.6/site-packages/pyNN/connectors.py", line 644, in connect
    weights = weights_generator.get(n, distance_matrix, create)
  File "/opt/software/pynn/0.7.4/lib/python2.6/site-packages/pyNN/connectors.py", line 135, in get_safe
    return self.check(self.extract(N, distance_matrix, sub_mask))
  File "/opt/software/pynn/0.7.4/lib/python2.6/site-packages/pyNN/connectors.py", line 118, in extract
    values = data[sub_mask]
IndexError: index 2 out of bounds 0<=index<2
```

This should happen with the FNPreC too, but nest uses its own implementation of the FNPreC.

Here's an example:

``` python
import numpy
import pyNN.nest as pynn
pynn.setup()

size = 3

pre = pynn.Population(size, pynn.IF_curr_alpha)
post = pynn.Population(size, pynn.IF_curr_alpha)

rng = pynn.NumpyRNG(42)

conn = pynn.FixedNumberPostConnector(2, weights=pynn.RandomDistribution(rng=pynn.NumpyRNG(42), distribution='uniform'))
proj = pynn.Projection(pre, post, conn)

print proj.getWeights(format='array')
```

**Comment by apdavison** [comment]
Closing, as we're no longer supporting the 0.7 branch
