### ISSUE TITLE
Failing to set FixedNumberPostConnector's weights from array/list

### ISSUE THREAD

**Issue by sbillaudelle** [NeuralEnsemble/PyNN#261]
I'm using PyNN 0.7.6dev and I'm encountering the following issue:
- Create two populations with eg. 10 neurons each
- Generate a numpy.array as a weights source (with 10^2 weights, just to be safe)
- Set up a FixedNumberPostConnector to connect each pre synaptic neuron to eg. 5 (<10!) post synaptic ones

The last step fails with the following traceback:

``` python
Traceback (most recent call last):
  File "foo.py", line 12, in <module>
    projection = pynn.Projection(pre, post, connector)
  File "/home/stein/Documents/Labs/Visions/pyHMF/pyhmf/lib/pyNN/nest/__init__.py", line 338, in __init__
    method.connect(self)
  File "/home/stein/Documents/Labs/Visions/pyHMF/pyhmf/lib/pyNN/connectors.py", line 649, in connect
    weights = weights_generator.get(n, distance_matrix, create)
  File "/home/stein/Documents/Labs/Visions/pyHMF/pyhmf/lib/pyNN/connectors.py", line 136, in get_safe
    return self.check(self.extract(N, distance_matrix, sub_mask))
  File "/home/stein/Documents/Labs/Visions/pyHMF/pyhmf/lib/pyNN/connectors.py", line 123, in extract
    values = numpy.array([self.source_iterator.next() for i in range(N)])[self.local_mask]
ValueError: too many boolean indices
```

Here's a minimal example:

``` python
import numpy
import pyNN.nest as pynn

SIZE = 10
N = 5

pre = pynn.Population(SIZE, pynn.IF_cond_alpha)
post = pynn.Population(SIZE, pynn.IF_cond_alpha)

weights = numpy.array([3.1415]*SIZE)
connector = pynn.FixedNumberPostConnector(N, weights=weights)
projection = pynn.Projection(pre, post, connector)
```

A solution for this issue should take #255 into consideration!

**Comment by apdavison** [comment]
Closing, as we're no longer supporting the 0.7 branch
