### ISSUE TITLE
Problem with nmodl mechanisms on Fedora

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/PyNN#329]
Hi,

I"ve built both NEURON and PyNN, and PyNN seemed to find nrnivmodl during the build process too:

```
('nrnivmodl found at', '/usr/bin/nrnivmodl')
Successfully compiled NEURON extensions.
```

but when I try to import neuron parts, I get this error: 

```
In [1]: from pyNN.neuron import simulator
NEURON -- VERSION 7.3 ansi (1078:2b0c984183df) 2014-04-04
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2014
See http://www.neuron.yale.edu/neuron/credits

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-47698f8cc50d> in <module>()
----> 1 from pyNN.neuron import simulator

/usr/lib/python2.7/site-packages/pyNN/neuron/__init__.py in <module>()
     14 from pyNN.space import Space
     15 from pyNN.random import NumpyRNG, GSLRNG, AbstractRNG
---> 16 from pyNN.neuron import simulator
     17 from pyNN.neuron.standardmodels.cells import *
     18 from pyNN.neuron.connectors import *

/usr/lib/python2.7/site-packages/pyNN/neuron/simulator.py in <module>()
    514
    515 mech_path = os.path.join(pyNN_path[0], 'neuron', 'nmodl')
--> 516 load_mechanisms(mech_path) # maintains a list of mechanisms that have already been imported
    517 state = _State()  # a Singleton, so only a single instance ever exists
    518 del _State

/usr/lib/python2.7/site-packages/pyNN/neuron/simulator.py in load_mechanisms(path)
     69             nrn_dll_loaded.append(path)
     70             return
---> 71     raise IOError("NEURON mechanisms not found in %s. You may need to run 'nrnivmodl' in this directory." % path)
     72
     73

IOError: NEURON mechanisms not found in /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl. You may need to run 'nrnivmodl' in this directory.

In [2]:
```

Would you know what I'm messing up here? This is the filelist for the PyNN package that I've built:

```
[asinha@localhost  PyNN(master %=)]$ rpmls python-pynn | grep neuron
drwxr-xr-x  /usr/lib/python2.7/site-packages/pyNN/neuron
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/__init__.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/__init__.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/__init__.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/cells.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/cells.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/cells.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/connectors.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/connectors.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/connectors.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nineml.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nineml.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nineml.pyo
drwxr-xr-x  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/adexp.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/alphaisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/alphasyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/expisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/gap.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/gsfa_grr.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/hh_traub.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/izhikevich.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/netstim2.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/refrac.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/reset.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/stdwa_guetig.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/stdwa_softlimits.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/stdwa_songabbott.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/stdwa_symm.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/stdwa_vogels2011.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/tmgsyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/tmisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/tsodyksmarkram.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/vecstim.mod
drwxr-xr-x  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/adexp.c
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/adexp.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/alphaisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/alphasyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/expisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/gap.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/gsfa_grr.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/hh_traub.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/izhikevich.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/mod_func.c
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/netstim2.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/refrac.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/reset.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/stdwa_guetig.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/stdwa_softlimits.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/stdwa_songabbott.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/stdwa_symm.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/stdwa_vogels2011.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/tmgsyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/tmisyn.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/tsodyksmarkram.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/nmodl/x86_64/vecstim.mod
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/populations.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/populations.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/populations.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/projections.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/projections.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/projections.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/recording.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/recording.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/recording.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/simulator.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/simulator.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/simulator.pyo
drwxr-xr-x  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/__init__.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/__init__.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/__init__.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/cells.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/cells.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/cells.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/electrodes.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/electrodes.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/electrodes.pyo
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/synapses.py
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/synapses.pyc
-rw-r--r--  /usr/lib/python2.7/site-packages/pyNN/neuron/standardmodels/synapses.pyo
```

I'm on a Fedora 21 x86_64 system:

```
[asinha@localhost  PyNN(master %=)]$ uname -r
3.17.0-0.rc7.git3.1.fc22.x86_64
```

**Comment by gdetor** [comment]
Hi,
I have a similar problem that I cannot resolve. My system's configuration is:
a Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux. I use Python 2.7.9 and I installed pyNN 0.7.5 and Neuron 7.3 (built from sources on my machine). When I'm trying to run the examples sources from pyNN Documentation page (http://neuralensemble.org/docs/PyNN/data_handling.html) I get the following message: 
```
NEURON -- VERSION 7.3 ansi (1078:2b0c984183df) 2014-04-04                                                │
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2014                                             │
See http://www.neuron.yale.edu/neuron/credits                                                            │
                                                                                                         │
loading membrane mechanisms from /usr/local/lib/python2.7/dist-packages/pyNN/neuron/nmodl/x86_64/.libs/li│
bnrnmech.so                                                                                              │
dlopen failed -                                                                                          │
/usr/local/lib/python2.7/dist-packages/pyNN/neuron/nmodl/x86_64/.libs/libnrnmech.so: undefined symbol: nr│
nmpi_myid                                                                                                │
Traceback (most recent call last):                                                                       │
  File "sim.py", line 1, in <module>                                                                     │
    import pyNN.neuron as sim  # can of course replace `nest` with `neuron`, `brian`, etc.               │
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/__init__.py", line 18, in <module>            │
    from pyNN.neuron.standardmodels.cells import *                                                       │
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/standardmodels/cells.py", line 13, in <module>│
    from pyNN.neuron.cells import StandardIF, SingleCompartmentTraub, RandomSpikeSource, VectorSpikeSourc│
e, BretteGerstnerIF, GsfaGrrIF                                                                           │
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/cells.py", line 43, in <module>               │
    class SingleCompartmentNeuron(nrn.Section):                                                          │
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/cells.py", line 47, in SingleCompartmentNeuron│
    'current':      { 'exp': h.ExpISyn, 'alpha': h.AlphaISyn },                                          │
AttributeError: 'hoc.HocObject' object has no attribute 'ExpISyn'   
```
I tried what you proposed in previous messages but still it doesn't work. Any idea? 
Thank you in advance.

**Comment by sanjayankur31** [comment]
> when i run nrnivmodl ，there is a error，（/usr/bin/ld: cannot find -lreadline）

You need to install the readline library provided by your distribution. On a Fedora system, for example:

```
sudo dnf install readline-devel
```

Closing this issue at the moment. I've not reproduced it in a while.

**Comment by lxdfrank** [comment]
thank you，i try it and solve the problem. Then i run nrnivmodl and it show successful.
However i run (import pyNN.neuron as sim),it shows (AttributeError: 'hoc.HocObject' object has no attribute 'ExpISyn')

**Comment by sanjayankur31** [comment]
You should file a separate issue for that one, or get in touch with folks on the mailing list for help: 
https://groups.google.com/forum/?fromgroups#!forum/neuralensemble
