### ISSUE TITLE
simple_STDP.py raises `AssertionError` when run with NEURON as simulator.

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#353]
One of the script examples, simple_STDP.py, raises the following `AssertionError` when run with NEURON as the simulator.  (Other errors appear to be generated when other simulators are used.)
```
$ python simple_STDP.py --plot-figure 'neuron'
NEURON -- VERSION 7.3 ansi (1078:2b0c984183df) 2014-04-04
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2014
See http://www.neuron.yale.edu/neuron/credits

loading membrane mechanisms from /usr/local/lib/python2.7/dist-packages/pyNN/neuron/nmodl/i686/.libs/libnrnmech.so
Additional mechanisms from files
 adexp.mod alphaisyn.mod alphasyn.mod expisyn.mod gap.mod gsfa_grr.mod hh_traub.mod izhikevich.mod netstim2.mod refrac.mod reset.mod stdwa_guetig.mod stdwa_softlimits.mod stdwa_songabbott.mod stdwa_symm.mod stdwa_vogels2011.mod tmgsyn.mod tmisyn.mod tsodyksmarkram.mod vecstim.mod
Traceback (most recent call last):
  File "simple_STDP.py", line 159, in <module>
    p2.write_data(filename, annotations={'script_name': __file__})
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.py", line 473, in write_data
    annotations=annotations)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/recording/__init__.py", line 321, in write
    data = self.get(variables, gather, filter_ids, clear, annotations=annotations)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/recording/__init__.py", line 287, in get
    data.segments.append(self._get_current_segment(filter_ids=filter_ids, variables=variables, clear=clear))
  File "/usr/local/lib/python2.7/dist-packages/pyNN/recording/__init__.py", line 275, in _get_current_segment
    assert segment.analogsignalarrays[0].t_stop - current_time < 2*sampling_period
AssertionError
```

**Comment by apdavison** [comment]
Fixed in 4756172
