### ISSUE TITLE
'None' has no attribute 'parameters' - when setting neuron positions directly

### ISSUE THREAD

**Issue by swenzel** [NeuralEnsemble/PyNN#364]
Using pyNN 0.8dev and NEST 2.6.0
I did not understand how the Grid3D structure works, so I decided to set the neurons' positions myself.
I thought it would be okay, since `Population.positions` has no underscore but when I run:
```python
import pyNN.nest as sim
import numpy as np

sim.setup()
sources = sim.Population(10, sim.SpikeSourcePoisson())
targets = sim.Population(135, sim.IF_cond_exp())
sim.Projection(sources, targets, sim.AllToAllConnector())
targets.positions = np.mgrid[0:3, 0:3, 0:15].reshape(3,-1)
targets.record('spikes')
sim.run(500)
targets.get_data()
sim.end()
```
I'm getting this error:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    targets.get_data()
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/common/populations.py", line 490, in get_data
    blk = self.recorder.get(variables, gather, self._record_filter, clear)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 298, in get
    data.segments.append(self._get_current_segment(filter_ids=filter_ids, variables=variables, clear=clear))
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 246, in _get_current_segment
    description=self.population.describe(),
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/common/populations.py", line 759, in describe
    return descriptions.render(engine, template, context)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/descriptions/__init__.py", line 55, in render
    return engine.render(template, context)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/descriptions/__init__.py", line 152, in render
    return template.render(context)
  File "/home/wenzel/.local/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/descriptions/templates/jinja2/population_default.txt", line 3, in top-level template code
    {%- for name,value in structure.parameters.items() %}
  File "/home/wenzel/.local/lib/python2.7/site-packages/jinja2/environment.py", line 372, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'parameters'
```

**Comment by apdavison** [comment]
This should now be fixed.

(By the way, `structure=Grid3D(aspect_ratioXZ=0.2)` gives the positions you wanted).
