### ISSUE TITLE
Error while running pyNN/neuron

### ISSUE THREAD

**Issue by jaesunseo** [NeuralEnsemble/PyNN#369]
I first installed neuron, and then PyNN, following the instructions.
While running a python code, I got the following error message.
Could you let me know what would be causing the problem?
Thank you.

Starting PyNN with simulator: neuron

-------------------------------------------------
---------- Creating neuron populations ----------
-------------------------------------------------
Traceback (most recent call last):
  File "network.py", line 200, in <module>
    stimulus = Population(1000, SpikeSourcePoisson(rate=100.0))
  File "/home/jseo28/.local/lib/python2.7/site-packages/pyNN/neuron/populations.py", line 81, in __init__
    structure, initial_values, label)
  File "/home/jseo28/.local/lib/python2.7/site-packages/pyNN/common/populations.py", line 643, in __init__
    self._create_cells()
  File "/home/jseo28/.local/lib/python2.7/site-packages/pyNN/neuron/populations.py", line 111, in _create_cells
    self.all_cells[i]._build_cell(self.celltype.model, params)
  File "/home/jseo28/.local/lib/python2.7/site-packages/pyNN/neuron/simulator.py", line 310, in _build_cell
    self._cell = cell_model(**cell_parameters)          # create the cell object
  File "/home/jseo28/.local/lib/python2.7/site-packages/neuron/__init__.py", line 170, in __new__
    return hoc.HocObject.__new__(cls, *args, **kwds)
RuntimeError: invalid keyword argument

**Comment by apdavison** [comment]
This is a problem with NEURON 7.4 (see http://www.neuron.yale.edu/phpBB/viewtopic.php?f=2&t=3377). There is a fix in the NEURON repository, but an updated package hasn't yet been released as far as I know.

For the time being, the easiest workaround is to use NEURON 7.3.
