### ISSUE TITLE
IndexError on empty spike_times for SpikeSourceArray

### ISSUE THREAD

**Issue by astoeckel** [NeuralEnsemble/PyNN#378]
Creating a SpikeSourceArray with no spikes

    sim.Population(1, sim.SpikeSourceArray, {"spike_times": []})

causes an IndexError:

	Traceback (most recent call last):
	  File "./run.py", line 55, in <module>
		output = sim.run(net)
	  File "/home/andreas/hbp-pynnless/pynnless/pynnless.py", line 769, in run
		populations[i] = self._build_population(network["populations"][i])
	  File "/home/andreas/hbp-pynnless/pynnless/pynnless.py", line 435, in _build_population
		res = self.sim.Population(count, type_, params)
	  File "/usr/lib/python2.7/site-packages/pyNN/nest/populations.py", line 104, in __init__
		super(Population, self).__init__(size, cellclass, cellparams, structure, initial_values, label)
	  File "/usr/lib/python2.7/site-packages/pyNN/common/populations.py", line 634, in __init__
		self.celltype = cellclass(**cellparams)
	  File "/usr/lib/python2.7/site-packages/pyNN/models.py", line 27, in __init__
		self.parameter_space.update(**parameters)
	  File "/usr/lib/python2.7/site-packages/pyNN/parameters.py", line 291, in update
		and not isinstance(value[0], Sequence)): # may be a more generic way to do it, but for now this special-casing seems like the most robust approach
	IndexError: list index out of range

Values of "count", "type_" and "params" in the 3rd stack-frame are

     	1 <class 'pyNN.nest.standardmodels.cells.SpikeSourceArray'> {'spike_times': []}

Probably you should search for more instances of "[0]" in the code, and make sure the invariant of "there is at least one" element is explicitly checked.

PyNN version is 0.8.

**Comment by astoeckel** [comment]
My workaround for this bug is to simply delete "spike_times" from the parameters if it is empty:

            if ("spike_times" in params) and (len(params["spike_times"]) == 0)):
                del params["spike_times"]
