### ISSUE TITLE
PyNN documentation for writing data to update

### ISSUE THREAD

**Issue by dguarino** [NeuralEnsemble/PyNN#422]
According to the docs, PyNN 0.8.1 should save in text file formats:
http://neuralensemble.org/docs/PyNN/fileformats.html

but, using the default example with the reported writing method:
p.printSpikes("my_spike_data.txt")

an error is generated:
Traceback (most recent call last):
  File "1layer.py", line 162, in <module>
    py.printSpikes("my_spike_data.txt")
  File "/home/do/Envs/pynn/local/lib/python2.7/site-packages/pyNN/core.py", line 55, in new_func
    return func(*args, **kwargs)
  File "/home/do/Envs/pynn/local/lib/python2.7/site-packages/pyNN/common/populations.py", line 498, in printSpikes
    self.write_data(file, 'spikes', gather)
  File "/home/do/Envs/pynn/local/lib/python2.7/site-packages/pyNN/common/populations.py", line 476, in write_data
    annotations=annotations)
  File "/home/do/Envs/pynn/local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 328, in write
    file = get_io(file)
  File "/home/do/Envs/pynn/local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 138, in get_io
    raise IOError("ASCII-based formats are not currently supported for output data. Try using the file extension '.pkl' or '.h5'")
IOError: ASCII-based formats are not currently supported for output data. Try using the file extension '.pkl' or '.h5'

**Comment by apdavison** [comment]
This file is outdated (hence listed under "Old documents"). Removed in 53601a6 to avoid confusion.
