### ISSUE TITLE
Type Index Out of Range For Projection In Multi-Threaded Nest

### ISSUE THREAD

**Issue by kennysharma** [NeuralEnsemble/PyNN#476]
PyNN 0.8.1 and Nest 2.10.0.

Do you have any idea what could cause this?

```
Traceback (most recent call last):
  File "../lib/python2.7/site-packages/pyNN/nest/projections.py", line 60, in __init__
    connector.connect(self)
  File "../lib/python2.7/site-packages/pyNN/nest/connectors.py", line 148, in connect
    return super(AllToAllConnector, self).connect(projection)
  File "../lib/python2.7/site-packages/pyNN/connectors.py", line 282, in connect
    self._connect_with_map(projection, connection_map)
  File "../lib/python2.7/site-packages/pyNN/connectors.py", line 248, in _connect_with_map
    self._standard_connect(projection, connection_map.by_column, distance_map)
  File "../lib/python2.7/site-packages/pyNN/connectors.py", line 230, in _standard_connect
    projection._convergent_connect(source_mask, col, **connection_parameters)
  File "../lib/python2.7/site-packages/pyNN/nest/projections.py", line 199, in _convergent_connect
    self._identify_common_synapse_properties()
  File "../lib/python2.7/site-packages/pyNN/nest/projections.py", line 230, in _identify_common_synapse_properties
    local_parameters = nest.GetStatus(sample_connection)[0].keys()
IndexError: tuple index out of range
```

The code within our application that causes this can be reduced to:

```python
import pyNN.nest as sim 

sim.setup(timestep=0.1, min_delay=0.1, max_delay=20.0, threads=8)

population = sim.Population(size=2, cellclass=sim.IF_cond_alpha())
view = sim.PopulationView(population, selector=slice(0L, 2L, None))

generator = sim.Population(1, sim.SpikeSourcePoisson(duration=float("inf"), start=0.0, rate=0.0))
sim.Projection(presynaptic_population=generator,
               postsynaptic_population=view,
               source=None,
               receptor_type='excitatory',
               connector=sim.AllToAllConnector(),
               synapse_type=sim.StaticSynapse(weight=0.00015, delay=0.1),
               label=None)

<repeated generator/projection below after other devices are created causes the error>
```

Important notes:

- I can't reproduce this via that minimal script, bit it happens 100% of the time in our code.

- The issue doesn't happen when threads=1

- This error only occurs the second time a generator/projection is created to the same population view.

- The simulation has never been ticked, this is just after creation of the network/initialization of a bunch of devices.

- There's no error on the first connection attempt, but it doesn't seem to actually be connected and producing spikes when the rate is set high (either via PyNN or Nest devices).

This may not at all be a PyNN issue, but I'm confused as to what we could be doing that would cause this error within PyNN. As I said it's the same code run twice that produces the backtrace, we're not changing any parameters or anything. Any thoughts?

**Comment by kennysharma** [comment]
I added some debug to "pyNN/nest/projections.py", it seems as though everything is being done correctly by PyNN - it's properly calling nest.Connect(...) properly in _convergent_connect(...) with the right source/target and synapse parameters.

The failure occurs because that connection is not returned by nest.GetConnections() in _identify_common_synapse_properties(), causing the tuple failure.

The calls are identical to those on a single threaded/configured nest, so this is a weird all around.

**Comment by kennysharma** [comment]
I'll ask on the nest-user mailing list and see if anyone has a suggestion for causes.

**Comment by kennysharma** [comment]
Closing this issue as not a PyNN bug, after further investigation everything seems to be identical at the Nest SLI command level, so this doesn't seem PyNN related at all. Sorry for the inconvenience.
