### ISSUE TITLE
SpikeSourceArray, spike_times=[0.1]

### ISSUE THREAD

**Issue by philipsgithub** [NeuralEnsemble/PyNN#503]
Hello,

my setup: PYNN 0.9.1, NEST 2.12.0.

I am trying to set a spike of a SpikeSourceArray to 0.1ms, but there is an error.

```
import pyNN.nest as sim
from pyNN.parameters import Sequence

sim.setup(timestep=0.1,spike_precision="on_grid")
times=Sequence([0.1])
#times=Sequence([0.1000000000000001])
source=sim.SpikeSourceArray(spike_times=times)
p1=sim.Population(1,source)
```
Error:
```
NESTError: BadProperty in SetDefaults_l_D: Setting status of model 'spike_generator': spike time cannot be set to 0.
```

If you uncomment the commented line it works. I don't know where 0.1 becomes 0. but my tests let assume it's somewhere in pynn.

Best Regards
Philip

**Comment by philipsgithub** [comment]
nest-test:
```
import nest
nest.ResetKernel()
source=nest.Create("spike_generator",1,{"spike_times": [0.1]})
nest.GetStatus(source)[0]["spike_times"]
```

**Comment by philipsgithub** [comment]
Is something wrong with my issue??

**Comment by apdavison** [comment]
@philipsgithub I don't understand your question. Are you wondering why no-one has replied to it in the past two weeks? (The answer being that a lot of people are on vacation!)

**Comment by apdavison** [comment]
The reason for this behaviour is that NEST spike sources are connected in PyNN via parrot neurons, because otherwise you can't use plastic synapses [*see footnote*]. The parrot neuron introduces an extra delay, which means you can't have spikes occur at `1.0 * min_delay` (as you already saw, NEST does not allow spikes at time zero).

The workaround is to reduce `min_delay`, e.g. in your case
```python
sim.setup(timestep = 0.05, min_delay=0.05, spike_precision="on_grid")
times = Sequence([0.1])
```

----
[footnote]
```python
# can't use plastic synapses with spike_generator
>>> a = nest.Create('spike_generator')
>>> b = nest.Create('iaf_psc_alpha')
>>> nest.Connect(a, b, 'all_to_all', 'stdp_synapse')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/docker/env/neurosci/lib/python3.4/site-packages/nest/lib/hl_api_helper.py", line 230, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/docker/env/neurosci/lib/python3.4/site-packages/nest/lib/hl_api_connections.py", line 350, in Connect
    sr('Connect')
  File "/home/docker/env/neurosci/lib/python3.4/site-packages/nest/__init__.py", line 117, in catching_sli_run
    raise _kernel.NESTError(encode(errorstring))
pynestkernel.NESTError: IllegalConnection in Connect_g_g_D_D: Creation of connection is not possible because:
Possible cause: only static synapse types may be used to connect devices.
```

**Comment by apdavison** [comment]
Leaving this ticket open, because PyNN should produce an informative error in this situation.

**Comment by philipsgithub** [comment]
@apdavison Thanks a lot for your explanation. Didn't know about the parrot neurons... A more informative error would be very helpful, I agree.
