### ISSUE TITLE
ValueError: shape mismatch: value array of shape (20,) could not be broadcast to indexing result of shape (0,)

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#507]
I am trying to run this code [here](http://neuralensemble.org/docs/PyNN/examples/small_network.html). I recently installed PyNN and brian on a newer machine. I have another machine which has same combo and it never gave me this error.  Everything was installed using pip install. 
```
Traceback (most recent call last):
  File "smallnet.py", line 81, in <module>
    sim.run(simtime)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/brian/simulator.py", line 57, in run_until
    self.run(tstop - self.t)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/brian/simulator.py", line 54, in run
    self.network.run(simtime * ms)
  File "/usr/local/lib/python2.7/dist-packages/brian/network.py", line 574, in run
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/brian/network.py", line 518, in update
    f()
  File "/usr/local/lib/python2.7/dist-packages/brian/neurongroup.py", line 546, in reset
    self._resetfun(self)
  File "/usr/local/lib/python2.7/dist-packages/brian/reset.py", line 328, in __call__
    V[neuronindices] = self.resetvalue
```

**Comment by appukuttan-shailesh** [comment]
This is (in all likelihood) to do with use of the latest version of numpy (v1.13). Use an older version (e.g. v1.12) for the time being, till PyNN is made compatible with v1.13.

**Comment by ruthvik92** [comment]
Thank you, i will try it out and get back!

**Comment by ruthvik92** [comment]
Hi, I tried Numpy 1.12 and it works.

**Comment by apdavison** [comment]
Judging by the traceback, and looking at the relevant variables using pdb, this problem is deep inside Brian, and is not PyNN-specific. Since I don't think Brian 1 is receiving bug fixes any more, and there is a workaround (using Numpy 1.12), I am going to close this ticket.
