### ISSUE TITLE
Error in PyNN 0.7 RandomDistribution when redrawing

### ISSUE THREAD

**Issue by rowleya** [NeuralEnsemble/PyNN#566]
I don't know if you are fixing PyNN 0.7 errors any more, but if you are, the following script fails:
```
from pyNN.random import RandomDistribution, NumpyRNG

rng = NumpyRNG(1)
delay_i2e = RandomDistribution(
    'normal', (1.9, 0.3), rng=rng, boundaries=[0.2, 2.8], constrain='redraw')

print delay_i2e.next(1000)
```
with:
```
Traceback (most recent call last):
  File "C:\Users\zzalsar4\git\PyNN7Examples\examples\test_rng.py", line 7, in <module>
    print delay_i2e.next(1000)
  File "C:\Users\zzalsar4\git\PyNN-0.7.5\PyNN7\pyNN\random.py", line 235, in next
    res[idx] = self.rng.next(n=n, distribution=self.name, parameters=self.parameters, mask_local=mask_local)
ValueError: shape mismatch: value array of shape (1000,) could not be broadcast to indexing result of shape (3,)
```

I believe the fix is to change line 235 from 
```
res[idx] = self.rng.next(n=n, distribution=self.name, parameters=self.parameters, mask_local=mask_local)
```
to:
```
res[idx] = self.rng.next(n=len(idx), distribution=self.name, parameters=self.parameters, mask_local=mask_local)
```

**Comment by apdavison** [comment]
Closing, as we're no longer supporting the 0.7 branch
