### ISSUE TITLE
Multiple panels in Figure

### ISSUE THREAD

**Issue by dguarino** [NeuralEnsemble/PyNN#613]
My code is creating several panels in a loop and then creating the figure.
Something like this (can produce a working example if necessary):
```python
for key,rec in populations.items():
     panels = []
     vm = data.filter(name = 'v')[0]
     panels.append( Panel(vm, ylabel="mV", xlabel="ms") )
     panels.append( Panel(data.spiketrains, xlabel="Time (ms)", xticks=True, markersize=1) )
     Figure( *panels ).save(folder+'/'+key+addon+".png")
```
This is the error:
```
Traceback (most recent call last):
  File "run.py", line 144, in <module>
    scores = h.analyse(params, opts.data_folder, str(comb), opts.remove)
  File "/home/domenico/thalamus/helpers.py", line 202, in analyse
    Figure( *panels ).save(folder+'/'+key+addon+".svg")
  File "/home/docker/env/thalamus/lib/python3.4/site-packages/pyNN/utility/plotting.py",
line 201, in __init__
    panel.plot(plt.subplot(gs[i, 0]))
  File "/home/docker/env/thalamus/lib/python3.4/site-packages/pyNN/utility/plotting.py",
line 256, in plot
    plot_signals(axes, datum, label_prefix=label, **properties)
  File "/home/docker/env/thalamus/lib/python3.4/site-packages/pyNN/utility/plotting.py",
line 83, in plot_signals
    for i in signal_array.channel_index.index.argsort():
AttributeError: 'numpy.ndarray' object has no attribute 'index'
```
My current (relevant) stack is installed by the Docker image neuralensemble/simulationx:
matplotlib==1.4.2
neo==0.7.0
numpy==1.15.4
parameters==0.2.1
Pillow==2.6.1
PyNN==0.9.2
quantities==0.12.2
requests==2.8.1
scipy==0.14.0
Sumatra==0.7.4

**Comment by apdavison** [comment]
yes, please could you attach a working example. It's not clear where `data` comes from

**Comment by apdavison** [comment]
@dguarino is this still an issue? If so, could you post a complete example?

**Comment by dguarino** [comment]
Not an issue anymore. 
Using the standard figure features :)
