### ISSUE TITLE
can not create population with brian2 backend

### ISSUE THREAD

**Issue by laurentperrinet** [NeuralEnsemble/PyNN#642]
while on the `brian2_dev`branch, using this minimal `test.py` script:

```
import sys
from pyNN.utility import get_script_args
# from brian2 import amp

simulator_name = get_script_args(1)[0]
exec("from pyNN.%s import *" % simulator_name)

# setup(timestep=0.01, min_delay=0.1)
setup(min_delay=0.1)

cells = Population(1, IF_curr_exp(v_rest = -65.0, v_thresh=-55.0, tau_refrac=5.0))#, i_offset=-1.0*amp))
```

with `python3 test.py brian2`results in an error logged by brian as : 

```
$ cat  /var/folders/0t/crx5yf1x3rd8378nbqbv00vc0000gn/T/brian_debug_w7m2y_i2.log
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: Logging to file: /var/folders/0t/crx5yf1x3rd8378nbqbv00vc0000gn/T/brian_debug_w7m2y_i2.log, copy of main script saved as: /var/folders/0t/crx5yf1x3rd8378nbqbv00vc0000gn/T/brian_script_pk5iqk91.py
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: Python interpreter: /usr/local/opt/python/bin/python3.7
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: Platform: darwin
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: brian version is: 2.2.2.1
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: numpy version is: 1.16.3
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: scipy version is: 1.2.1
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: weave version is: not installed
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: sympy version is: 1.4
2019-05-13 10:01:15,873 DIAGNOSTIC brian2: python version is: 3.7.3 (default, Mar 27 2019, 09:23:39)
[Clang 10.0.0 (clang-1000.11.45.5)]
2019-05-13 10:01:15,874 DEBUG      brian2: Cache size for target "cython": 0 MB
2019-05-13 10:01:16,395 DIAGNOSTIC brian2.core.names: Created object of class Network with name network
2019-05-13 10:01:16,395 DIAGNOSTIC brian2.core.names: Created object of class Clock with name clock
2019-05-13 10:01:16,396 DIAGNOSTIC brian2.core.clocks: Created clock clock with dt=0.0001
2019-05-13 10:01:16,545 DIAGNOSTIC brian2.core.names: Created object of class NetworkOperation with name networkoperation
2019-05-13 10:01:16,546 DIAGNOSTIC brian2.core.base: Created BrianObject with name networkoperation, clock=Clock(dt=100. * usecond, name='defaultclock'), when=start, order=0
2019-05-13 10:01:16,551 ERROR      brian2: Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/0t/crx5yf1x3rd8378nbqbv00vc0000gn/T/brian_debug_w7m2y_i2.log  Additionally, you can also include a copy of the script that was run, available at: /var/folders/0t/crx5yf1x3rd8378nbqbv00vc0000gn/T/brian_script_pk5iqk91.py Thanks!
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    cells = Population(1, IF_curr_exp(v_rest = -65.0, v_thresh=-55.0, tau_refrac=5.0))#, i_offset=-1.0*amp))
  File "/usr/local/lib/python3.7/site-packages/pyNN/common/populations.py", line 663, in __init__
    self._create_cells()
  File "/usr/local/lib/python3.7/site-packages/pyNN/brian2/populations.py", line 67, in _create_cells
    parameter_space = self.celltype.native_parameters
  File "/usr/local/lib/python3.7/site-packages/pyNN/standardmodels/__init__.py", line 72, in native_parameters
    return self.translate(self.parameter_space)
  File "/usr/local/lib/python3.7/site-packages/pyNN/standardmodels/__init__.py", line 88, in translate
    pval = D['forward_transform'](**_parameters)
  File "/usr/local/lib/python3.7/site-packages/pyNN/brian2/standardmodels/cells.py", line 102, in <lambda>
    ('v_rest',     'v_rest',     lambda **p: p["v_rest"] * mV, lambda **p: p["v_rest"] / mV),
  File "/usr/local/lib/python3.7/site-packages/lazyarray.py", line 56, in wrapped_meth
    raise ValueError("shape mismatch: objects cannot be broadcast to a single shape")
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

any clue?

**Comment by appukuttan-shailesh** [comment]
> Note: Use a version of LazyArray that includes the following change:
> 
> NeuralEnsemble/lazyarray@38850fc
> 

See here: https://github.com/NeuralEnsemble/PyNN/issues/632#issue-436261009

**Comment by apdavison** [comment]
I've just made a new release of lazyarray, so
`pip install -U lazyarray`
should be enough

**Comment by laurentperrinet** [comment]
this bit of code now works, thanks - now for the rest!
