### ISSUE TITLE
Error in test_create_with_homogeneous_common_properties

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#659]
The test `test_create_with_homogeneous_common_properties` in `unittests/test_nest.py` was being skipped for some time as it was causing a core dump with the NEST master branch at the time.

On un-skipping it, the core dump is gone, but there is now an error:
```
======================================================================
ERROR: Native synapse with array-like parameters and CommonProperties.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/NeuralEnsemble/PyNN/test/unittests/test_nest.py", line 112, in test_create_with_native_synapse
    synapse_type=self.native_synapse_type())
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/nest/projections.py", line 59, in __init__
    connector.connect(self)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/nest/connectors.py", line 148, in connect
    return super(AllToAllConnector, self).connect(projection)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/connectors.py", line 282, in connect
    self._connect_with_map(projection, connection_map)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/connectors.py", line 248, in _connect_with_map
    self._standard_connect(projection, connection_map.by_column, distance_map)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/connectors.py", line 230, in _standard_connect
    projection._convergent_connect(source_mask, col, **connection_parameters)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/nest/projections.py", line 229, in _convergent_connect
    self._set_common_synapse_property(name, value)
  File "/home/travis/build/NeuralEnsemble/PyNN/pyNN/nest/projections.py", line 293, in _set_common_synapse_property
    nest.SetDefaults(self.nest_synapse_model, name, value)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nest/lib/hl_api_models.py", line 136, in SetDefaults
    sr('/{0} exch SetDefaults'.format(model))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nest/ll_api.py", line 132, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.ll_api.NESTErrors.TypeMismatch: ('TypeMismatch in SetDefaults_l_D: Expected datatype: intvectortype or arraytype\nProvided datatype: integertype', 'TypeMismatch', <SLILiteral: SetDefaults_l_D>, ': Expected datatype: intvectortype or arraytype\nProvided datatype: integertype')
```

**Comment by apdavison** [comment]
(this applies to both nest-dev and master)
